# Generated by Django 6.0.3 on 2026-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default=1, upload_to='subjects/'),
            preserve_default=False,
        ),
    ]
