# Generated by Django 6.0.3 on 2026-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_published',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
