# Generated by Django 6.0.3 on 2026-04-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_topic_is_published_subject_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
    ]
