# Generated by Django 6.0.3 on 2026-04-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_university_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='image',
        ),
    ]
