# Generated by Django 6.0.3 on 2026-04-14 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCategory',
            new_name='CourseLevel',
        ),
        migrations.AlterModelOptions(
            name='courselevel',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.courselevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='specializations',
            field=models.ManyToManyField(related_name='courses', to='courses.specialization'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='image',
            field=models.ImageField(blank=True, upload_to='specialization/'),
        ),
    ]
