# Generated by Django 6.0.3 on 2026-04-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='image',
        ),
    ]
